### ISSUE TITLE
how to setup for multi page app

### ISSUE THREAD

**Issue by rajanmagar** [colbyfayock/html-webpack-partials-plugin#10]
That was awesome example but please describe for multi page app.

**Comment by colbyfayock** [comment]
@rajanmagar can you describe a little more in detail what you're hoping to figure out how to do?

**Comment by rajanmagar** [comment]
@colbyfayock I want to implement google tag manager script for other pages too. This example is only for one page.

**Comment by colbyfayock** [comment]
did you try out this example? https://github.com/colbyfayock/html-webpack-partials-plugin/tree/master/examples/basic-multi

should be able to utilize the same partial files for the multi-page approach like you see there. if that's not working you can share a repo giving an example of what's not working and I can debug

**Comment by colbyfayock** [comment]
gonna close this out, feel free to reopen if you found an issue :)
