### ISSUE TITLE
Question: Multiple partials for one page ?

### ISSUE THREAD

**Issue by Legends** [colbyfayock/html-webpack-partials-plugin#11]
I have setup my project to use the partials plugin for loading content pages (`body-xyz.html`).
Now  I have one `layout.ejs` page which `requires` other html templates, which in whole represent the layout page, means: this layout page is the basis for all pages.

Now I use your plugin for every` html-webpack-plugin` configuration to dynamically inject the respective `body.html`.

Unfortunately after upgrading my project to use latest beta version of the ` html-webpack-plugin` ,
I cannot `require` anymore. [see issue](https://github.com/jantimon/html-webpack-plugin/issues/1325#issuecomment-569517342).

**Now my question:**
I would delete all require calls in my layout page and use your plugin to inject the respective partial I need.
I would delete this for example: 
 `  ${require('../../partials/nav.html')} // inside of layout.ejs

Is there a way to configure multiple partials with respective location set for a certain page?

Btw. Appreciate your plugin !

**Comment by Legends** [comment]
This should actually be possible by defining multiple entries in settings object pointing to the same file

**Comment by colbyfayock** [comment]
ah didn't realize upgrading to the latest beta is what was breaking that, should have figured, but glad to know that. I tried to take a shot at figuring this out a while back but I wasn't getting anywhere, I can another shot and see if I can find anything. maybe I can make use of the info in that linked issue, i'll follow up with any additional details in the other issue here
