### ISSUE TITLE
Update readme with template options

### ISSUE THREAD

**Issue by syedjafri** [colbyfayock/html-webpack-partials-plugin#4]
Thank you for a great plugin ! 
I see in the example folder that we can pass in template options. Can you please provide some explanation on its usage in readme

**Comment by colbyfayock** [comment]
I added a missing one for `template_filename`, but I THINK the "settings" section covers everything 🤔
https://github.com/colbyfayock/html-webpack-partials-plugin#settings

Any particular you noticed that weren't being mentioned? Is the confusing part the clarity about being able to pass in a single object or an array of objects?

**Comment by colbyfayock** [comment]
Yeah, I could see how that might be confusing. I was trying to use a property name that was both logical within the Partials plugin scope but still show the relationship to the HTML Webpack Plugin. I tweaked the description a little bit, hope that helps a little.

Check this example out: https://github.com/colbyfayock/html-webpack-partials-plugin/blob/master/examples/page-template/webpack.config.js
